server:
  port: 8080


eureka:
  client:
    register-with-eureka: true
    fetch-registry:   true
    serviceUrl: 
     defaultZone: http://localhost:8761/eureka
     
     
     
spring:
  application:
    name:   API-GATEWAY   
  
  
  
  cloud:
    gateway:
      routes:
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE              # http://localhost:8181/api/department/**
        predicates:
        - Path=/api/department/**
        
        
        
      - id: USER-SERVICE
        uri: lb://USER-SERVICE              # http://localhost:8282/api/users/**
        predicates:
        - Path=/api/users/**
        
        
        
        
        